### ISSUE TITLE
TypeError: Cannot read property 'results' of undefined

### ISSUE THREAD

**Issue by shenqihui** [matthias-schuetz/karma-htmlfile-reporter#11]
Hello, i find some problem when test file has some error.  
And this will break karma test task.

```
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: alter
  at /home/vagrant/github/karma_test/src/hello_src.js:12

undefined
ERROR [karma]: [TypeError: Cannot read property 'results' of undefined]
TypeError: Cannot read property 'results' of undefined
    at onBrowserComplete (/home/vagrant/github/karma_test/node_modules/karma-htmlfile-reporter/index.js:90:10)
    at null.<anonymous> (/home/vagrant/github/karma_test/node_modules/karma/lib/events.js:14:22)
    at emit (events.js:117:20)
    at onComplete (/home/vagrant/github/karma_test/node_modules/karma/lib/browser.js:142:13)
    at Socket.<anonymous> (/home/vagrant/github/karma_test/node_modules/karma/lib/events.js:14:22)
    at Socket.emit [as $emit] (events.js:117:20)
    at SocketNamespace.handlePacket (/home/vagrant/github/karma_test/node_modules/karma/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/vagrant/github/karma_test/node_modules/karma/node_modules/socket.io/lib/manager.js:488:38)
    at WebSocket.Transport.onMessage (/home/vagrant/github/karma_test/node_modules/karma/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/home/vagrant/github/karma_test/node_modules/karma/node_modules/socket.io/lib/transports/websocket/default.js:36:10)
```

And i find the problem.  
link this https://github.com/matthias-schuetz/karma-htmlfile-reporter/blob/master/index.js#L87

```
this.onBrowserComplete = function(browser) {
    var suite = suites[browser.id];
    var result = browser.lastResult;

    suite['results'].txt(result.total + ' tests / ');
    suite['results'].txt((result.disconnected || result.error ? 1 : 0) + ' errors / ');
    suite['results'].txt(result.failed + ' failures / ');
    suite['results'].txt(result.skipped + ' skipped / ');
    suite['results'].txt('runtime: ' + ((result.netTime || 0) / 1000) + 's');

    if (allMessages.length > 0) {
        suite.ele('tr', {class:'system-out'}).ele('td', {colspan:'3'}).raw('<strong>System output:</strong><br />' + allMessages.join('<br />'));
    }
  };
```
here `suite ` is  undefined.
And i think we should test it before use just using if statement.

**Comment by matthias-schuetz** [comment]
Sorry for the late response, I've tested and added your code changes, it works!
Thanks for your attention.
