### ISSUE TITLE
"TypeError: browsers.forEach is not a function" while running test.

### ISSUE THREAD

**Issue by sanjummathew** [matthias-schuetz/karma-htmlfile-reporter#30]
I recently upgraded to Angular 6. Now I'm unable to get html report while running unit tests due to this error:

```
ERROR [karma-server]: TypeError: browsers.forEach is not a function
    at HTMLReporter.onRunStart (C:\webserver\GIT\gco2ng\node_modules\karma-htmlfile-reporter\index.js:113:14)
    at createHtmlResults (C:\webserver\GIT\gco2ng\node_modules\karma-htmlfile-reporter\index.js:66:12)
    at HTMLReporter.onBrowserError (C:\webserver\GIT\gco2ng\node_modules\karma-htmlfile-reporter\index.js:123:5)
    at Server.<anonymous> (C:\webserver\GIT\gco2ng\node_modules\karma\lib\events.js:40:26)
    at emitTwo (events.js:131:20)
    at Server.emit (events.js:214:7)
    at Browser.disconnect (C:\webserver\GIT\gco2ng\node_modules\karma\lib\browser.js:170:18)
    at Browser.onDisconnect (C:\webserver\GIT\gco2ng\node_modules\karma\lib\browser.js:103:12)
    at Socket.socket.on (C:\webserver\GIT\gco2ng\node_modules\karma\lib\browser.js:196:46)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Socket.emit (C:\webserver\GIT\gco2ng\node_modules\socket.io\lib\socket.js:142:10)
    at Socket.onclose (C:\webserver\GIT\gco2ng\node_modules\socket.io\lib\socket.js:454:8)
    at Client.onclose (C:\webserver\GIT\gco2ng\node_modules\socket.io\lib\client.js:254:24)
    at emitTwo (events.js:131:20)
    at Socket.emit (events.js:214:7)
```

**Versions that i'm using:**
`jasmine-core: 3.3.0,`
`karma: 3.1.1`
`karma-htmlfile-reporter: 0.3.7,`
`karma-jasmine: 2.0.0,`

**Comment by sanjummathew** [comment]
I tried commenting inside all karma events and interestingly, none of the events are getting triggered, but when i refresh Karma-runner, it stops with the above error because `createHtmlResults` calls `onRunStart` by passing an object as parameter and not array.

**Comment by sanjummathew** [comment]
My issue is resolved. It was because I had mentioned wrong `angularCli` path in karma.conf.js.
